NiceApp/Controllers/UserhomeController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NiceApp.Data;
using NiceApp.Models.DataModel;
using NiceApp.Services.EmailServices;
using NiceApp.Services.UserhomeService;

namespace NiceApp.Controllers
{
    public class UserhomeController : Controller
    {
        private readonly ILogger<UserhomeController> _logger;
        private IUserhomeService _UserhomeService;
        private readonly UserManager<AppUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly IEmailSenderServices _emailSenderServices;
        private readonly AppDbContext _db;
        public UserhomeController(
            UserManager<AppUser> userManager,
            SignInManager<AppUser> signInManager,
            IEmailSenderServices emailSenderServices,
            AppDbContext db,
            RoleManager<IdentityRole> roleManager,
            ILogger<UserhomeController> logger, 
            IUserhomeService UserhomeService)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _emailSenderServices = emailSenderServices;
            _roleManager = roleManager;
            _db = db;

            _logger = logger;
            _UserhomeService = UserhomeService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }
        [HttpGet]
        public IActionResult AllVehicles()
        {


            return View();
        }
        [HttpPost]
        public IActionResult AllVehicles(string VehicleType)
        {
            //ViewBag.AllVehicleType = VehicleType;

            var VehicleTypeList = _UserhomeService.GetAllVehicleFromType(VehicleType);
            //ViewBag.VehicleList = VehicleTypeList;

            return View(VehicleTypeList);
        }


        public IActionResult AllStations()
        {
            ViewBag.AllVehiclesListStation = new SelectList(_UserhomeService.GetAllStation(), "Id", "StationName");
            return View();
        }
        [HttpPost]
        public IActionResult AllStations(int station)
        {

            ViewBag.AllVehiclesListStation = new SelectList(_UserhomeService.GetAllStation(), "Id", "StationName");
          
            var VehicleSationList = _UserhomeService.GetAllVehicleFromStation(station);
            ViewBag.VehicleStList = VehicleSationList;
            return View();
        }

    }
}

NiceApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NiceApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NiceApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NiceApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - NiceApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

NiceApp/Views/Shared/_NewLayout.cshtml
@using NiceApp.Models.DataModel
@using Microsoft.AspNetCore.Identity

@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager


<!DOCTYPE html>
<html lang="en">

<head>
    <title>Supriye</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="assets/img/apple-icon.png">
    <link rel="shortcut icon" type="image/x-icon" href="~/assets/img/favicon.ico">

    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/css/templatemo.css">
    <link rel="stylesheet" href="~/assets/css/custom.css">

    <!-- Load fonts style after rendering the layout styles -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap">
    <link rel="stylesheet" href="~/assets/css/fontawesome.min.css">

</head>

<body>



    <!-- Start Top Nav -->
    <nav class="navbar navbar-expand-lg bg-dark navbar-light d-none d-lg-block" id="templatemo_nav_top">
        <div class="container text-light">
            <div class="w-100 d-flex justify-content-between">
                <div>
                    <i class="fa fa-envelope mx-2"></i>
                    <a class="navbar-sm-brand text-light text-decoration-none " href="http://www.gmail.com">amatyasupriye@gmail.com</a>
                </div>
                <div class="topnav-right">
                    <i class="fa fa-phone mx-2"></i>
                    <a class="navbar-sm-brand text-light text-decoration-none">9869073871</a>
                </div>

            </div>
        </div>
    </nav>
    <!-- Close Top Nav -->
    <!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-light shadow">
        <div class="container d-flex justify-content-between align-items-center">

            <a class="navbar-brand text-success logo h1 align-self-center" href="index.html">
                Supriye XD
            </a>

            <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#templatemo_main_nav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="align-self-center collapse navbar-collapse flex-fill  d-lg-flex justify-content-lg-between" id="templatemo_main_nav">
                <div class="flex-fill">
                    <ul class="nav navbar-nav d-flex justify-content-between mx-lg-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="Userhome">Home</a>
                        </li>
                        @*     <li class="nav-item">
                        <a class="nav-link" asp-action="Login" asp-controller="Account">Login</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" asp-action="Register" asp-controller="Account">Register</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link" asp-action="About" asp-controller="Userhome">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Contact" asp-controller="Userhome">Contact</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="#">Hello @UserManager.GetUserName(User)</a>
                            </li>
                            <li class="nav-item">
                                <form id="logoutForm" method="post" class="form-inline" asp-controller="Account"
                                  asp-action="LogOff">
                                    <button type="submit" class="btn nav-link">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                           
                        }
                    </ul>

                </div>
                <div class="navbar align-self-center d-flex">
                    <div class="d-lg-none flex-sm-fill mt-3 mb-4 col-7 col-sm-auto pr-3">
                        <div class="input-group">
                            <input type="text" class="form-control" id="inputMobileSearch" placeholder="Search ...">
                            <div class="input-group-text">
                                <i class="fa fa-fw fa-search"></i>
                            </div>
                        </div>
                    </div>
                    <a class="nav-icon d-none d-lg-inline" href="#" data-bs-toggle="modal" data-bs-target="#templatemo_search">
                        <i class="fa fa-fw fa-search text-dark mr-2"></i>
                    </a>

                </div>
                @*  <div>
                <div class="nav-item">
                <a  class="fa fa-user" asp-action="Login" asp-controller="Login">Sign In</a>
                </div>
                </div>*@
            </div>

        </div>
    </nav>
    <!-- Close Header -->
    @RenderBody()

    <!-- Modal -->
    <div class="modal fade bg-white" id="templatemo_search" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="w-100 pt-1 mb-5 text-right">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="" method="get" class="modal-content modal-body border-0 p-0">
                <div class="input-group mb-2">
                    <input type="text" class="form-control" id="inputModalSearch" name="q" placeholder="Search ...">
                    <button type="submit" class="input-group-text bg-success text-light">
                        <i class="fa fa-fw fa-search text-white"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>
    <!-- Start Footer -->
    <footer class="bg-dark" id="tempaltemo_footer">
        <div class="container">
            <div class="row">

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-success border-bottom pb-3 border-light logo">Supriye XD</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li>
                            <i class="fas fa-map-marker-alt fa-fw"></i>
                            Kathmandu, Nepal
                        </li>
                        <li>
                            <i class="fa fa-phone fa-fw"></i>
                            <a class="text-decoration-none">9869073871</a>
                        </li>
                        <li>
                            <i class="fa fa-envelope fa-fw"></i>
                            <a class="text-decoration-none" href="">amatyasupriye@gmail.com</a>
                        </li>
                    </ul>
                </div>

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-light border-bottom pb-3 border-light">Type of Automobiles You can Rent</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li><a class="text-decoration-none" href="#">Cars</a></li>
                        <li><a class="text-decoration-none" href="#">SUVs</a></li>
                        <li><a class="text-decoration-none" href="#">Jeeps</a></li>
                        <li><a class="text-decoration-none" href="#">Motorcycles</a></li>
                        <li><a class="text-decoration-none" href="#">Scooter</a></li>
                        <li><a class="text-decoration-none" href="#">Bus</a></li>
                        <li><a class="text-decoration-none" href="#">All in Electric, Gas or Hybrid</a></li>
                        <li><a class="text-decoration-none" href="#">And Many More.</a></li>
                    </ul>
                </div>

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-light border-bottom pb-3 border-light">Further Info About Us</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li><a class="text-decoration-none" href="#">Home</a></li>
                        <li><a class="text-decoration-none" href="#">About Us</a></li>
                        <li><a class="text-decoration-none" href="#">Contact</a></li>
                    </ul>
                </div>

            </div>


        </div>

        <div class="w-100 bg-black py-3">
            <div class="container">
                <div class="row pt-2">
                    <div class="col-12">
                        <p class="text-left text-light">
                            Copyright &copy; 2022 Supriye
                            | Designed by <a rel="sponsored" href="https://www.instagram.com/supriy.ayyy/" target="_blank">Supriye Amatya</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>

    </footer>
    <!-- End Footer -->
    <!-- Start Script -->
    <script src="assets/js/jquery-1.11.0.min.js"></script>
    <script src="assets/js/jquery-migrate-1.2.1.min.js"></script>
    <script src="assets/js/bootstrap.bundle.min.js"></script>
    <script src="assets/js/templatemo.js"></script>
    <script src="assets/js/custom.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <!-- End Script -->
</body>
</html>